
# Introducci√≥n al _testing_

¬°Hola! Hasta ahora venimos programando sin parar, y en m√°s de una ocasi√≥n nuestro c√≥digo no ha funcionado como lo dese√°bamos. Quiz√°s ten√≠amos mal escrito el nombre de una funci√≥n o una variable y se produc√≠a un `NameError`. O quiz√°s, comet√≠amos un error de sintaxis y nos top√°bamos con un `SyntaxError`. O peor a√∫n, ten√≠amos un _bug_ (üêõ bicho, en ingl√©s): nuestro c√≥digo no lanzaba ning√∫n error, pero sin embargo no hac√≠a lo que deb√≠a: una cuenta era incorrecta, faltaba o sobraba un elemento en una lista, y as√≠.

Es m√°s: posiblemente _rara vez_ nuestros programas hayan hecho lo que deben en el primer intento y hayamos tenido que escribirlo y reescribirlo varias veces hasta lograr el resultado deseado üîÅ. En definitiva, _errar es humano_ y debemos preparanos para ello. ¬°Por eso mismo siempre debemos probar nuestro c√≥digo! Por ejemplo, si dentro de un archivo `descuento.py` tenemos una funci√≥n como la siguiente...

```python
def aplicar_descuento_2x1(cantidad, precio_base):
  """
  Aplica el descuento 2 X 1 a un precio: los pares de productos los cobra a la mitad de precio
  """
  if cantidad % 2 == 0:
    return precio_base * cantidad / 2
  else:
    return precio_base * (cantidad - 1) / 2
```

...¬øc√≥mo la probar√≠amos? La forma m√°s sencilla es cargarla en nuestro int√©rprete con `python -i descuento.py` y luego _someterla_  a diferentes pruebas:

  * Si la cantidad es cero, el precio deber√≠a ser cero, sin importar la cantidad
  * Si la cantidad es 2 y el precio base es $100, el precio final deber√≠a ser $100
  * Si la cantidad es 4 y el precio base es $150, el precio final deber√≠a ser $300
  * Si la cantidad es 1 y el precio base es $200, el precio final deber√≠a ser $200 (no hubo descuento)
  * etc...

Esto lo podr√≠amos _traducir_ as√≠:


```python
>>> aplicar_descuento_2x1(0, 450)
0.0
>>> aplicar_descuento_2x1(2, 100)
100
>>> aplicar_descuento_2x1(4, 150)
300
>>> aplicar_descuento_2x1(1, 200)
0.0 # ¬°ups!
```

En otras palabras, algunas pruebas arrojaron resultados correctos y otras, no:

  * ‚úîÔ∏è Si la cantidad es cero, el precio deber√≠a ser cero, sin importar la cantidad
  * ‚úîÔ∏è Si la cantidad es 2 y el precio base es $100, el precio final deber√≠a ser $100
  * ‚úîÔ∏è Si la cantidad es 4 y el precio base es $150, el precio final deber√≠a ser $300
  * ‚ùå Si la cantidad es 1 y el precio base es $200, el precio final deber√≠a ser $200 (no hubo descuento)

¬øQu√© hacemos ahora que encontramos un _bug_? Deber√≠amos volver a nuestro c√≥digo, revisarlo y descubrir el error. En nuestro caso, era la falta de un `+ 1`:

```python
def aplicar_descuento_2x1(cantidad, precio_base):
  """
  Aplica el descuento 2 X 1 a un precio: los pares de productos los cobra a la mitad de precio
  """
  if cantidad % 2 == 0:
    return precio_base * cantidad / 2
  else:
    return precio_base * (1 + (cantidad - 1) / 2)
```

¬øPero qu√© nos garantiza que esta vez no hayamos cometido ning√∫n error? ¬°Absolutamente nada! Es decir, deber√≠amos volver a probar el caso que fall√≥ anteriormente, para asegurarnos de que hayamos corregido el problema:

```python
>>> aplicar_descuento_2x1(1, 200)
200.0 # ¬°bien! ¬°pasamos la prueba!
```

¬°Pero eso no es suficiente! Perfectamente podr√≠amos haber _roto_ accidentalmente los casos que antes s√≠ funcionaban (lo que se conoce como errores de _regresi√≥n_):

```python
>>> aplicar_descuento_2x1(0, 450)
0.0
>>> aplicar_descuento_2x1(2, 100)
100
>>> aplicar_descuento_2x1(4, 150)
300
```

Reci√©n ahora podemos decir que hemos probado todo con resultados satisfactorios üò´:

  * ‚úîÔ∏è Si la cantidad es cero, el precio deber√≠a ser cero, sin importar la cantidad
  * ‚úîÔ∏è Si la cantidad es 2 y el precio base es $100, el precio final deber√≠a ser $100
  * ‚úîÔ∏è Si la cantidad es 4 y el precio base es $150, el precio final deber√≠a ser $300
  * ‚úîÔ∏è Si la cantidad es 1 y el precio base es $200, el precio final deber√≠a ser $200 (no hubo descuento)

Como vemos, todo esto es tedioso y propenso a error. ¬øY qu√© hacemos cuando algo es as√≠? ¬°Programamos!

## Pruebas unitarias automatizadas

Justamente porque probar es necesario, pero al mismo tiempo hacerlo correctamente y luego de cada cambio es muy molesto y aburrido, es que existen las pruebas unitarias automatizadas: se trata de _programar_ nuestras pruebas, usando una herramienta especializada.

En Python usaremos [`pytest`](https://docs.pytest.org/en/7.1.x/), la cual podemos instalar de la siguiente forma:

```bash
$ pip install pytest
```

Luego de √©sto, podremos escribir, en el mismo directorio que nuestro archivo principal, otro llamado `test_descuento.py`, en que el que escribiremos nuestras _pruebas unitarias automatizadas_, es decir:

  * **pruebas** sobre nuestro programa;
  * que eval√∫an detalladamente peque√±as cada una de sus **unidades** (partes), como por ejemplo cada funci√≥n o cada procedimiento;
  * y que se pueden ejecutar de forma **autom√°tica**, tantas veces como se desee.

Para ello primero debemos _importar_ nuestro c√≥digo, es decir, leerlo de su archivo y traerlo a aquel que contiene las pruebas...

```python
from descuento import *
```

... y luego, escribiremos cada una de nuestras pruebas unitarias automatizadas, o pruebas unitarias, o simplemente, _tests_:

```python
def test_el_precio_es_cero_cuando_cuando_cantidad_es_cero():
  assert aplicar_descuento_2x1(0, 450) == 0
```

Como vemos, un test consiste simplemente en un procedimiento, con ciertas caracter√≠sticas:

  1. como todo procedimiento, no debe devolver nada;
  2. su nombre debe empezar con  `test`;
  3. debe probar un escenario de nuestro inter√©s, y realizar validaciones con el comando `assert`;
  4. y debe tener un nombre que exprese qu√© es lo que se est√° probando.

En nuestro ejemplo:

  1. el test anterior no devuelve nada;
  2. su nombre empieza con `test`;
  3. existe para probar el primer escenario que discutimos previamente: _si la cantidad es cero, el precio deber√≠a ser cero_.
  4. y finalmente verifica mediante el comando `assert` que efectivamente la funci√≥n retorne el valor esperado (`0`): si la condici√≥n booleana es falsa, el test fallar√°, pero si es verdadera, el test ser√° exitoso.

¬øY c√≥mo hacemos para ejecutar nuestras pruebas? ¬°Usando el comando `pytest`!

```bash
$ pytest
============================= test session starts =============================
platform linux -- Python 3.8.10, pytest-7.1.3, pluggy-1.0.0
collected 1 item

test_descuento.py .                                                     [100%]

============================== 1 passed in 0.01s ==============================
```

¬°Est√° vivo! Esto nos indica que el test se ejecut√≥ correctamente üéä.

Si ahora quisieramos escribir otro test m√°s, para la segunda situaci√≥n (_Si la cantidad es 2 y el precio base es $100, el precio final deber√≠a ser $100_), deber√≠amos escribirlo as√≠:

```python
def test_el_precio_es_100_cuando_cantidad_es_2_y_precio_es_100():
  assert aplicar_descuento_2x1(2, 100) == 100
```

Y nuevamente podemos ejecutar todos nuestros tests:

```bash
$ pytest
============================= test session starts =============================
platform linux -- Python 3.8.10, pytest-7.1.3, pluggy-1.0.0
collected 2 items

test_descuento.py ..                                                    [100%]

============================== 2 passed in 0.01s ==============================
```

¬øY que pasar√≠a si prob√°ramos el caso _Si la cantidad es 1 y el precio base es $200, el precio final deber√≠a ser $200_...

```python
def test_el_precio_es_200_cuando_la_cantidad_es_1_y_el_precio_base_es_200():
  assert aplicar_descuento_2x1(1, 200) == 200
```

... y lo prob√°ramos con la primera versi√≥n de nuestro c√≥digo?


```
$ pytest
============================= test session starts =============================
platform linux -- Python 3.8.10, pytest-7.1.3, pluggy-1.0.0
collected 3 items

test_descuento.py ..F                                                   [100%]

================================== FAILURES ===================================
____ test_el_precio_es_200_cuando_la_cantidad_es_1_y_el_precio_base_es_200 ____

    def test_el_precio_es_200_cuando_la_cantidad_es_1_y_el_precio_base_es_200():
>     assert aplicar_descuento_2x1(1, 200) == 200
E     assert 0.0 == 200
E      +  where 0.0 = aplicar_descuento_2x1(1, 200)

test_descuento.py:10: AssertionError
=========================== short test summary info ===========================
FAILED test_descuento.py::test_el_precio_es_200_cuando_la_cantidad_es_1_y_el_precio_base_es_200
========================= 1 failed, 2 passed in 0.06s =========================
```

üí£ ¬°El test estalla! Pero lo bueno es que nos lo indica con precisi√≥n: nos dice cu√°ntos tests fallaron y cu√°ntos no, qu√© errores hubo y d√≥nde. Con todo esto ahora corregir nuestro c√≥digo (recordar que faltaba el `+ 1`) y volver a correr el test es sencillo:

```
$ pytest
============================ test session starts =============================
platform linux -- Python 3.8.10, pytest-7.1.3, pluggy-1.0.0
collected 3 items

test_descuento.py ...                                                  [100%]

============================= 3 passed in 0.01s ==============================
```

## Conclusiones

A modo de cierre, podemos sacar algunas conclusiones:

  1. üêû Cometer errores es inevitable; m√°s que tratar a toda costa que nuestro c√≥digo sea "perfecto", preferiremos que nuestro c√≥digo est√© probado.
  2. ‚Ü©Ô∏è Cuando hacemos un cambio al c√≥digo, a√∫n cuando sea para realizar una correcci√≥n, es necesario volver a probarlo todo nuevamente para evitar errores de regresi√≥n.
  3. üßë‚Äçüî¨ Las pruebas manuales son muy importantes, pero son tediosas de hacer una y otra vez.
  4. ü§ñ Las pruebas unitarias automatizadas requieren poner un poco m√°s de esfuerzo, pero podemos reutilizarlas y ejecutarlas indefinidamente.
  5. üî® `pytest` es una herramienta que permite escribir pruebas unitarias automatizadas en Python.
  6. üß™ Los tests en `pytest` se escriben como procedimientos cuyo nombre empieza con `test` y tienen un `assert`.
